version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - laravel-net
    volumes:
      - .:/var/www/html # Adicione esta linha para compartilhar os arquivos do projeto

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    networks:
      - laravel-net
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

networks:
  laravel-net:
